Repository ruzickap/ruzickap.github.io, pull requests merged in 2023-04, with the labels that each got.

#102 style: bit typo on a mention
  _posts/2022/2022-11-27-cheapest-amazon-eks.md
Labels: size/XS

#108 feat(posts): add secrets-store-csi-driver+reloader
  .github/workflows/gh-pages-build.yml
  .github/workflows/post_tests.yml
  .markdown-link-check.json
  README.md
  _posts/2022/2022-09-02-my-sony-a7-iv-settings.md
  _posts/2022/2022-11-27-cheapest-amazon-eks.md
  _posts/2022/2022-12-24-amazon-eks-karpenter-tests.md
  _posts/2023/2023-01-15-ftp-and-sony-camera.md
  _posts/2023/2023-03-08-trivy-operator-grafana.md
  _posts/2023/2023-03-20-velero-and-cert-manager.md
  _posts/2023/2023-04-01-secrets-store-csi-driver-reloader.md
  _tabs/about.md
  assets/img/posts/2023/2023-04-01-secrets-store-csi-driver-reloader/aws-secrets-manager-01-secrets-kuardsecret.avif
  assets/img/posts/2023/2023-04-01-secrets-store-csi-driver-reloader/aws-secrets-manager-02-secrets-kuardsecret.avif
  assets/img/posts/2023/2023-04-01-secrets-store-csi-driver-reloader/aws-secrets-manager-03-secrets-kuardsecret.avif
  assets/img/posts/2023/2023-04-01-secrets-store-csi-driver-reloader/kuard-env.avif
  assets/img/posts/2023/2023-04-01-secrets-store-csi-driver-reloader/kuard-fs-mnt-secrets-store-KuardSecret.avif
  lychee.toml
Labels: size/XL

#113 fix(lychee): Fix lychee exclude and enable cache
  .github/workflows/gh-pages-build.yml
  .github/workflows/links.yml
  lychee.toml
Labels: size/M

#119 feat(renovate): Add kube-prometheus-stack helm chart version automerge
  .github/renovate.json5
Labels: size/S
