Repository ruzickap/ruzickap.github.io, pull requests merged in 2023-08, with the labels that each got.

#160 feat(posts): add cilium-amazon-eks
  .github/workflows/post_tests.yml
  _posts/2022/2022-11-27-cheapest-amazon-eks.md
  _posts/2023/2023-03-20-velero-and-cert-manager.md
  _posts/2023/2023-08-03-cilium-amazon-eks.md
Labels: size/XXL

#165 feat(renovate): add autoupdate of grafana dashboards
  .github/renovate.json5
  _posts/2022/2022-11-27-cheapest-amazon-eks.md
  _posts/2023/2023-03-08-trivy-operator-grafana.md
  _posts/2023/2023-03-20-velero-and-cert-manager.md
  _posts/2023/2023-08-03-cilium-amazon-eks.md
  lychee.toml
Labels: size/L

#167 fix(posts): fix delete part for cheapest-amazon-eks
  .github/renovate.json5
  _posts/2022/2022-11-27-cheapest-amazon-eks.md
Labels: size/XS

#169 feat(posts): add private network to the cilium-amazon-eks
  .gitignore
  _posts/2022/2022-11-27-cheapest-amazon-eks.md
  _posts/2023/2023-08-03-cilium-amazon-eks.md
Labels: size/M

#170 feat(posts): remove old ingress-nginx annotations
  _posts/2022/2022-11-27-cheapest-amazon-eks.md
  _posts/2023/2023-08-03-cilium-amazon-eks.md
Labels: size/XS

#171 docs(posts): bit misspell in Secrets and Cilium post
  _posts/2023/2023-04-01-secrets-store-csi-driver-reloader.md
  _posts/2023/2023-08-03-cilium-amazon-eks.md
Labels: size/S
