Repository ruzickap/ruzickap.github.io, pull requests merged in 2024-05, with the labels that each got.

#271 feat(posts): add exploit-vulnerability-wordpress-plugin-kali-linux
  .github/workflows/gh-pages-build.yml
  .github/workflows/post_tests.yml
  .gitleaks.toml
  _posts/2023/2023-03-20-velero-and-cert-manager.md
  _posts/2023/2023-04-01-secrets-store-csi-driver-reloader.md
  _posts/2023/2023-08-03-cilium-amazon-eks.md
  _posts/2023/2023-09-25-secure-cheap-amazon-eks.md
  _posts/2024/2023-04-27-exploit-vulnerability-wordpress-plugin-kali-linux.md
  assets/img/posts/2024/2023-04-27-exploit-vulnerability-wordpress-plugin-kali-linux/kali-linux-metasploit-exploit-wp_backup_migration_php_filter.avif
  assets/img/posts/2024/2023-04-27-exploit-vulnerability-wordpress-plugin-kali-linux/kali-linux-metasploit-wordpress_scanner.avif
Labels: size/L

#272 fix(posts): fix date in exploit-vulnerability-wordpress-plugin-kali-linux
  .gitleaks.toml
  _posts/2024/2024-04-27-exploit-vulnerability-wordpress-plugin-kali-linux.md
  assets/img/posts/2024/2024-04-27-exploit-vulnerability-wordpress-plugin-kali-linux/kali-linux-metasploit-exploit-wp_backup_migration_php_filter.avif
  assets/img/posts/2024/2024-04-27-exploit-vulnerability-wordpress-plugin-kali-linux/kali-linux-metasploit-wordpress_scanner.avif
Labels: size/XS

#274 refactor(renovate): remove push/branches/"!renovate/*"
  .github/workflows/renovate.yml
Labels: size/XS

#276 feat(chirpy): upgrade jekyll-theme-chirpy
  .github/workflows/gh-pages-build.yml
  Gemfile
  _config.yml
  _data/share.yml
  _posts/2024/2024-04-27-exploit-vulnerability-wordpress-plugin-kali-linux.md
Labels: size/M

#277 feat(posts): eks-with-pod-identities cleanup
  _posts/2024/2024-04-27-exploit-vulnerability-wordpress-plugin-kali-linux.md
  _posts/2024/2024-05-03-secure-cheap-amazon-eks-with-pod-identities.md
  lychee.toml
Labels: size/S

#280 docs(posts): bit misspell namespaces
  _posts/2024/2024-05-03-secure-cheap-amazon-eks-with-pod-identities.md
Labels: size/XS
